// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-equipment-manage/backend/internal/dao/internal"
)

// equipmentDao is the data access object for the table plugin_linapro_equipment_manage_equipment.
// You can define custom methods on it to extend its functionality as needed.
type equipmentDao struct {
	*internal.EquipmentDao
}

var (
	// Equipment is a globally accessible object for table plugin_linapro_equipment_manage_equipment operations.
	Equipment = equipmentDao{internal.NewEquipmentDao()}
)

// Add your custom methods and functionality below.
