// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-equipment-manage/backend/internal/dao/internal"
)

// maintenanceDao is the data access object for the table plugin_linapro_equipment_manage_maintenance.
// You can define custom methods on it to extend its functionality as needed.
type maintenanceDao struct {
	*internal.MaintenanceDao
}

var (
	// Maintenance is a globally accessible object for table plugin_linapro_equipment_manage_maintenance operations.
	Maintenance = maintenanceDao{internal.NewMaintenanceDao()}
)

// Add your custom methods and functionality below.
