// =================================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// ViewSession is the golang structure for table view_session.
type ViewSession struct {
	Id         int64      `json:"id"         orm:"id"          description:"Watch session ID"`
	TenantId   int        `json:"tenantId"   orm:"tenant_id"   description:"Owning tenant ID, 0 means PLATFORM"`
	LiveId     int64      `json:"liveId"     orm:"live_id"     description:"Watched live content ID"`
	SessionKey string     `json:"sessionKey" orm:"session_key" description:"Anonymous viewer session key generated by the browser, unique across the plugin"`
	CreatedAt  *time.Time `json:"createdAt"  orm:"created_at"  description:"Creation time"`
	UpdatedAt  *time.Time `json:"updatedAt"  orm:"updated_at"  description:"Latest heartbeat time"`
}
