-- 002: live share and view stats schema
-- 002：直播分享与在线观看统计数据结构

-- Purpose: Stores anonymous viewer watch sessions for heartbeat upserts and
--          aggregate online/total view statistics.
-- 用途：存储匿名观众观看会话，支撑心跳幂等 upsert 与在线/累计观看聚合统计。

CREATE TABLE IF NOT EXISTS plugin_linapro_live_manage_view_session (
    "id"          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "tenant_id"   INT          NOT NULL DEFAULT 0,
    "live_id"     BIGINT       NOT NULL,
    "session_key" VARCHAR(64)  NOT NULL,
    "created_at"  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE plugin_linapro_live_manage_view_session IS 'Anonymous viewer watch session table for live viewing statistics';
COMMENT ON COLUMN plugin_linapro_live_manage_view_session."id" IS 'Watch session ID';
COMMENT ON COLUMN plugin_linapro_live_manage_view_session."tenant_id" IS 'Owning tenant ID, 0 means PLATFORM';
COMMENT ON COLUMN plugin_linapro_live_manage_view_session."live_id" IS 'Watched live content ID';
COMMENT ON COLUMN plugin_linapro_live_manage_view_session."session_key" IS 'Anonymous viewer session key generated by the browser, unique across the plugin';
COMMENT ON COLUMN plugin_linapro_live_manage_view_session."created_at" IS 'Creation time';
COMMENT ON COLUMN plugin_linapro_live_manage_view_session."updated_at" IS 'Latest heartbeat time';

-- One row per browser session: the heartbeat upsert business key.
-- 每个浏览器会话一行：心跳 upsert 的业务键。
CREATE UNIQUE INDEX IF NOT EXISTS uk_plugin_linapro_live_manage_view_session_session_key
    ON plugin_linapro_live_manage_view_session ("session_key");

-- Serves both the online count (live_id equality + updated_at range) and the
-- total view count (live_id prefix) aggregates.
-- 同时服务在线计数（live_id 等值 + updated_at 范围）与累计计数（live_id 前缀）聚合。
CREATE INDEX IF NOT EXISTS idx_plugin_linapro_live_manage_view_session_live_updated
    ON plugin_linapro_live_manage_view_session ("live_id", "updated_at");
