// =================================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"time"

	"github.com/gogf/gf/v2/frame/g"
)

// ViewSession is the golang structure of table plugin_linapro_live_manage_view_session for DAO operations like Where/Data.
type ViewSession struct {
	g.Meta     `orm:"table:plugin_linapro_live_manage_view_session, do:true"`
	Id         any        // Watch session ID
	TenantId   any        // Owning tenant ID, 0 means PLATFORM
	LiveId     any        // Watched live content ID
	SessionKey any        // Anonymous viewer session key generated by the browser, unique across the plugin
	CreatedAt  *time.Time // Creation time
	UpdatedAt  *time.Time // Latest heartbeat time
}
