// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-book-manage/backend/internal/dao/internal"
)

// bookDao is the data access object for the table plugin_linapro_book_manage_book.
// You can define custom methods on it to extend its functionality as needed.
type bookDao struct {
	*internal.BookDao
}

var (
	// Book is a globally accessible object for table plugin_linapro_book_manage_book operations.
	Book = bookDao{internal.NewBookDao()}
)

// Add your custom methods and functionality below.
