// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-book-manage/backend/internal/dao/internal"
)

// borrowDao is the data access object for the table plugin_linapro_book_manage_borrow.
// You can define custom methods on it to extend its functionality as needed.
type borrowDao struct {
	*internal.BorrowDao
}

var (
	// Borrow is a globally accessible object for table plugin_linapro_book_manage_borrow operations.
	Borrow = borrowDao{internal.NewBorrowDao()}
)

// Add your custom methods and functionality below.
