// This file declares the public watch-statistics request/response DTOs used
// by the linapro-live-manage viewer H5 page. The endpoint is anonymous: no
// JWT and no permission tag are required, and the route group intentionally
// omits the host auth, tenancy, and permission middlewares.

package v1

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Heartbeat API

// HeartbeatReq defines the anonymous watch-heartbeat request. The session key
// is generated by the browser and persisted in sessionStorage so refreshing
// the page does not inflate the total count.
type HeartbeatReq struct {
	g.Meta     `path:"/view/heartbeat" method:"post" tags:"LiveView" summary:"Record one viewer watch heartbeat" dc:"Record one anonymous viewer watch session heartbeat for the currently playable public live of the requested room and return the refreshed aggregate counters. Sessions are deduplicated by the browser session key, so repeated heartbeats never inflate the total view count. Rooms without a publicly playable live return zero counters without recording anything, keeping unknown rooms indistinguishable from empty content. The push URL and other administrative fields are never exposed."`
	RoomCode   string `json:"roomCode" v:"required" dc:"Live room code, unique within the tenant" eg:"MAIN-HALL"`
	TenantId   *int   `json:"tenantId" dc:"Tenant ID used to scope the anonymous query; required when the tenant plugin is enabled, where 0 selects the platform tenant; ignored when the tenant plugin is disabled" eg:"1"`
	SessionKey string `json:"sessionKey" v:"required" dc:"Browser-generated anonymous viewer session key persisted in sessionStorage; 1 to 64 characters" eg:"3f2c9a8e-7d41-4b6f-9a2e-8c1d5f7b3a90"`
}

// HeartbeatRes defines the aggregate counters returned after recording the
// heartbeat.
type HeartbeatRes struct {
	OnlineCount int64 `json:"onlineCount" dc:"Watch sessions with a heartbeat inside the last 60 seconds" eg:"3"`
	TotalViews  int64 `json:"totalViews" dc:"Deduplicated watch sessions recorded for the live" eg:"42"`
}
