// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// ViewSessionDao is the data access object for the table plugin_linapro_live_manage_view_session.
type ViewSessionDao struct {
	table    string             // table is the underlying table name of the DAO.
	group    string             // group is the database configuration group name of the current DAO.
	columns  ViewSessionColumns // columns contains all the column names of Table for convenient usage.
	handlers []gdb.ModelHandler // handlers for customized model modification.
}

// ViewSessionColumns defines and stores column names for the table plugin_linapro_live_manage_view_session.
type ViewSessionColumns struct {
	Id         string // Watch session ID
	TenantId   string // Owning tenant ID, 0 means PLATFORM
	LiveId     string // Watched live content ID
	SessionKey string // Anonymous viewer session key generated by the browser, unique across the plugin
	CreatedAt  string // Creation time
	UpdatedAt  string // Latest heartbeat time
}

// viewSessionColumns holds the columns for the table plugin_linapro_live_manage_view_session.
var viewSessionColumns = ViewSessionColumns{
	Id:         "id",
	TenantId:   "tenant_id",
	LiveId:     "live_id",
	SessionKey: "session_key",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
}

// NewViewSessionDao creates and returns a new DAO object for table data access.
func NewViewSessionDao(handlers ...gdb.ModelHandler) *ViewSessionDao {
	return &ViewSessionDao{
		group:    "default",
		table:    "plugin_linapro_live_manage_view_session",
		columns:  viewSessionColumns,
		handlers: handlers,
	}
}

// DB retrieves and returns the underlying raw database management object of the current DAO.
func (dao *ViewSessionDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of the current DAO.
func (dao *ViewSessionDao) Table() string {
	return dao.table
}

// Columns returns all column names of the current DAO.
func (dao *ViewSessionDao) Columns() ViewSessionColumns {
	return dao.columns
}

// Group returns the database configuration group name of the current DAO.
func (dao *ViewSessionDao) Group() string {
	return dao.group
}

// Ctx creates and returns a Model for the current DAO. It automatically sets the context for the current operation.
func (dao *ViewSessionDao) Ctx(ctx context.Context) *gdb.Model {
	model := dao.DB().Model(dao.table)
	for _, handler := range dao.handlers {
		model = handler(model)
	}
	return model.Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rolls back the transaction and returns the error if function f returns a non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note: Do not commit or roll back the transaction in function f,
// as it is automatically handled by this function.
func (dao *ViewSessionDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
