// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-oa-approval/backend/internal/dao/internal"
)

// flowNodeDao is the data access object for the table plugin_linapro_oa_approval_flow_node.
// You can define custom methods on it to extend its functionality as needed.
type flowNodeDao struct {
	*internal.FlowNodeDao
}

var (
	// FlowNode is a globally accessible object for table plugin_linapro_oa_approval_flow_node operations.
	FlowNode = flowNodeDao{internal.NewFlowNodeDao()}
)

// Add your custom methods and functionality below.
