// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-oa-approval/backend/internal/dao/internal"
)

// flowDao is the data access object for the table plugin_linapro_oa_approval_flow.
// You can define custom methods on it to extend its functionality as needed.
type flowDao struct {
	*internal.FlowDao
}

var (
	// Flow is a globally accessible object for table plugin_linapro_oa_approval_flow operations.
	Flow = flowDao{internal.NewFlowDao()}
)

// Add your custom methods and functionality below.
