// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-oa-approval/backend/internal/dao/internal"
)

// requestDao is the data access object for the table plugin_linapro_oa_approval_request.
// You can define custom methods on it to extend its functionality as needed.
type requestDao struct {
	*internal.RequestDao
}

var (
	// Request is a globally accessible object for table plugin_linapro_oa_approval_request operations.
	Request = requestDao{internal.NewRequestDao()}
)

// Add your custom methods and functionality below.
