// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-live-manage/backend/internal/dao/internal"
)

// announcementDao is the data access object for the table plugin_linapro_live_manage_announcement.
// You can define custom methods on it to extend its functionality as needed.
type announcementDao struct {
	*internal.AnnouncementDao
}

var (
	// Announcement is a globally accessible object for table plugin_linapro_live_manage_announcement operations.
	Announcement = announcementDao{internal.NewAnnouncementDao()}
)

// Add your custom methods and functionality below.
