// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-live-manage/backend/internal/dao/internal"
)

// bibleVerseDao is the data access object for the table plugin_linapro_live_manage_bible_verse.
// You can define custom methods on it to extend its functionality as needed.
type bibleVerseDao struct {
	*internal.BibleVerseDao
}

var (
	// BibleVerse is a globally accessible object for table plugin_linapro_live_manage_bible_verse operations.
	BibleVerse = bibleVerseDao{internal.NewBibleVerseDao()}
)

// Add your custom methods and functionality below.
