// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-live-manage/backend/internal/dao/internal"
)

// bibleBookDao is the data access object for the table plugin_linapro_live_manage_bible_book.
// You can define custom methods on it to extend its functionality as needed.
type bibleBookDao struct {
	*internal.BibleBookDao
}

var (
	// BibleBook is a globally accessible object for table plugin_linapro_live_manage_bible_book operations.
	BibleBook = bibleBookDao{internal.NewBibleBookDao()}
)

// Add your custom methods and functionality below.
