// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-live-manage/backend/internal/dao/internal"
)

// liveDao is the data access object for the table plugin_linapro_live_manage_live.
// You can define custom methods on it to extend its functionality as needed.
type liveDao struct {
	*internal.LiveDao
}

var (
	// Live is a globally accessible object for table plugin_linapro_live_manage_live operations.
	Live = liveDao{internal.NewLiveDao()}
)

// Add your custom methods and functionality below.
