// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-live-manage/backend/internal/dao/internal"
)

// roomDao is the data access object for the table plugin_linapro_live_manage_room.
// You can define custom methods on it to extend its functionality as needed.
type roomDao struct {
	*internal.RoomDao
}

var (
	// Room is a globally accessible object for table plugin_linapro_live_manage_room operations.
	Room = roomDao{internal.NewRoomDao()}
)

// Add your custom methods and functionality below.
