// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-linapro-live-manage/backend/internal/dao/internal"
)

// viewSessionDao is the data access object for the table plugin_linapro_live_manage_view_session.
// You can define custom methods on it to extend its functionality as needed.
type viewSessionDao struct {
	*internal.ViewSessionDao
}

var (
	// ViewSession is a globally accessible object for table plugin_linapro_live_manage_view_session operations.
	ViewSession = viewSessionDao{internal.NewViewSessionDao()}
)

// Add your custom methods and functionality below.
